package me.nickp0is0n.easylocalizelite.ui;

import javax.swing.*;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ItemListener;

public class ParserSettingsForm extends JFrame {
    private JCheckBox ignoreCommentsCheckBox;
    private JCheckBox ignoreCopyrightHeaderCheckBox;
    private JPanel panel1;

    public ParserSettingsForm() {
        setContentPane(panel1);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public void setIgnoreCommentsCheckBoxOnEditListener(ItemListener listener) {
        ignoreCommentsCheckBox.addItemListener(listener);
    }

    public void setIgnoreCopyrightHeaderCheckBoxOnEditListener(ItemListener listener) {
        ignoreCopyrightHeaderCheckBox.addItemListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 10, 0, 0), -1, -1));
        ignoreCommentsCheckBox = new JCheckBox();
        ignoreCommentsCheckBox.setIconTextGap(10);
        ignoreCommentsCheckBox.setText("Ignore comments");
        panel1.add(ignoreCommentsCheckBox, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ignoreCopyrightHeaderCheckBox = new JCheckBox();
        ignoreCopyrightHeaderCheckBox.setIconTextGap(10);
        ignoreCopyrightHeaderCheckBox.setText("Ignore copyright header");
        panel1.add(ignoreCopyrightHeaderCheckBox, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
